### PR TITLE
first API

### PR DESCRIPTION
**Pull request by Oxunjon1029**
This is REST API that I did . Please review it , and if there is any problems or mistakes , comment

### CODE REVIEW

**Comment by AudriusBaltusis** [comment]
Please exclude node_modules from commit

**Comment by Oxunjon1029** [comment]
I excluded node_modules from commit

**Comment by AudriusBaltusis** [comment]
Postman collection looks incomplete

**Comment by Oxunjon1029** [comment]
Yea , I didnt make all requests , but I 'm gonna add changes continuesly

**Comment by Oxunjon1029** [comment]
May I merge test branch to the main branch?

**Comment by AudriusBaltusis** [comment]
Once you will update Postman collection, then I will approve PR. Now task is incomplete

**Comment by AudriusBaltusis** [comment]
Any update on this?

**Comment by Oxunjon1029** [comment]
I completed postman collection, could you see that, please?

**Review by AudriusBaltusis — APPROVED** [review]

**Comment by Oxunjon1029** [comment]
Thank you!

**Comment by Oxunjon1029** [comment]
Could you review my second homework? I made a pull request

**Pull request merged**
